### ISSUE TITLE
Updates available

### ISSUE THREAD

**Issue by fredZen** [danielsz/sente-system#3]
Hi again

I wanted to use this with a recent version of Sente, so I ported the example. Then I did some more component-izing, because I didn’t really like the idea of the server accesing the system through a global var. Only then did I discover that this project had been [deprecated ](https://github.com/danielsz/sente-system/issues/2) in favor of system-websocket.

Anyway, here are the changes I made to sente-system:

1. [Added a deprecation notice](https://github.com/fredZen/sente-system/commit/1c05648a5ff34876bca4378247c9144e1033aede) to the README file
2. [Re-synced](https://github.com/fredZen/sente-system/commit/7b5d1bfd35e7f13527b0e7f1d120faadf843b7ed) with the upstream demo from Sente
3. [Componentized the server](https://github.com/fredZen/sente-system/commit/d6274bb799bcc15843ce0087b3b01650bcf82593)

Would you be interested in me issuing a pull-request for either of these?

**Comment by danielsz** [comment]
Hi Fred, 

Looks great. I'll be very happy to take your PR. Thank you very much!

No need for 1, I'll restate the purpose of `sente-boot`, `sente-system` and `system-websocket`. Each has different knowledge requirements. 
No need to know anything about `system` for `sente-boot`. 

Now that you did this work on `sente-system` it will be more difficult to explain the difference between it and `system-websocket`, but that's a good problem to have :-)
